/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package El.gatoo;


import MyLogic.MainLogic;
import javax.swing.UIManager;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String args[]) {
        
        //Changed

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainLogic mainLogic = MainLogic.getMainLogic();
                mainLogic.TBR();
            }
        });
    }
}
